Update the README, move the specification
redhat-developer/opencompose-old pull request #52
Opened 2017-01-06 15:15 UTC by cdrage

This commit updates the README to include an example as well as a more
outlined / straight-to-the-point approach of explaining Open Compose.

Minor changes include adding a space between Open Compose as well as
moving the specification file to a single file in the root directory
named SPECIFICATION.asc

2017-01-12 13:37 UTC, pradeepto requested changes

2017-01-12 13:37 UTC, pradeepto commented on README.md
@cdrage I am not sure if I would like to mention Docker Compose.

2017-01-12 13:37 UTC, pradeepto commented on README.md
> +Open Compose is an open standardised format for defining multi-container applications. Using a `.yaml` defined file, you create and start all your required services in one run command. This allows de
It is OpenCompose and not Open Compose.

2017-01-12 13:37 UTC, pradeepto commented on README.md
> +We are looking for ideas, proposals, comments and feedback on Open Compose. Please use GitHub issues to file issues or proposals.
@cdrage OpenCompose and not Open Compose.

2017-01-12 14:26 UTC, cdrage commented on README.md
I don't think this will cause any bad press / impact. Mentioning Docker Compose outlines exactly what we're suppose to do.

2017-01-12 14:26 UTC, cdrage commented on README.md
> +We are looking for ideas, proposals, comments and feedback on Open Compose. Please use GitHub issues to file issues or proposals.
Boo :( This is the official wording right?

2017-01-12 14:28 UTC, cdrage commented
@pradeepto Updated based on your review.

2017-01-12 15:03 UTC, pradeepto commented on README.md
@cdrage It was something like that because we wanted that kind of UX. But we are moving away. The phrase "alternative to Docker Compose" is the problem. The current idea is not to be an alternative to Docker Compose and rather be a first class citizen in the k8s/oc world.

2017-01-12 16:37 UTC, cdrage commented on README.md
@pradeepto Okay. Saying `Open Compose is similar to Docker Compose`?

Honestly, right now, Open Compose is pretty much a 1-1 copy of Docker Compose with the exception of volumes.

2017-01-13 05:20 UTC, pradeepto commented on README.md
@cdrage That is what we would like to change. And it was a copy because the original goal was to be similar or use it as inspiration.

2017-01-13 14:55 UTC, cdrage commented
@pradeepto please review again, updated the readme.

2017-01-18 14:13 UTC, cdrage commented
ping @pradeepto

2017-01-18 15:43 UTC, kadel commented on README.md
> +OpenCompose is an open standardised format for defining multi-container applications. Using a `.yaml` defined file, you create and start all your required services in one run command. This allows dev
Our positioning changed a bit and I don't think that its right to say that OpenCompose is alternative to Docker Compose.

2017-01-18 15:52 UTC, cdrage commented on README.md
> +OpenCompose is an open standardised format for defining multi-container applications. Using a `.yaml` defined file, you create and start all your required services in one run command. This allows dev
@kadel what has our positioning changed to?

2017-01-18 17:11 UTC, pradeepto commented on README.md
> +OpenCompose is an open standardised format for defining multi-container applications. Using a `.yaml` defined file, you create and start all your required services in one run command. This allows dev
@cdrage A "Higher Level Abstraction" to define microservices declaratively and deploy the services on OpenShift/Kubernetes."

The new vision for OpenCompose is to be something that is accepted by Kubernetes and OpenShift community as a standard worklow for developers who would like to deploy their applications on k8s/oc without knowing much about k8s/oc fundamentals. The User Experience of OpenCompose should be as simple as Docker Compose. The language of the spec (yaml) should be such that developers can start using it after reading a simple tutorial or document and should not have to read or understand k8s/oc documentation.

Also, a very important tenet of OpenCompose will be that it shouldn't become yet another k8s/oc resource since it defeats the purpose. OpenCompose's vocabulary of directives needs to be just as much that is really required and strictly nothing more than that. It has be to simple to use for any developer or operations person.

2017-02-17 13:35 UTC, closed without merging